version: '3'

services:
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_db
      MYSQL_USER: flowerpot
      MYSQL_PASSWORD: password
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    networks:
      - app-network
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: api
    ports:
      - "8888:8888"
    volumes:
      - ./api:/go/src/app
    networks:
      - app-network
  web:
    image: nginx:latest
    container_name: web
    depends_on:
      - db
      - api
    ports:
      - "80:80"
    volumes:
      - ./html:/etc/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge