version: '3'

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: api
    ports:
      - "8888:8888"
    volumes:
      - ./api:/go/src/app
    networks:
      - app-network