version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8888:8888"
    volumes:
      - ./:/go/src/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge